---
title: Descubriendo las bestias de la Venezuela Prehistórica
categories:
  - Español
  - Paleontology
---
Probablemente tú también pasaste por una fase de afición por los dinosaurios en la niñez; esas cautivadoras criaturas de un pasado distante de las cuales sólo nos quedan sus restos convertidos en rocas. Si diésemos un paso más, desatando nuestra imaginación y quisiéramos escribir una versión más regional del clásico Parque Jurásico de Michael Crichton, contaríamos con perezosos gigantes, aves con dientes diminutos (aunque técnicamente sería más correcto llamarlos pseudodientes), tigres colmillos de sable, primates, serpientes marinas, y por supuesto, algunos dinosaurios en el sentido más tradicional. Al norte de Sudamérica contamos con una riqueza de fósiles que seguramente era totalmente desconocida para ti. Desde el Laboratorio de Paleontología del Instituto Venezolano de Investigaciones Científicas (IVIC), sus investigadores se han dedicado a traer al presente los restos de estas bestias prehistóricas.

Continúa leyendo el resto del artículo en [Revista Persea](https://revistapersea.com/ciencias-de-la-vida/descubriendo-las-bestias-de-la-venezuela-prehistrica/)